"""initial

Revision ID: 51dfa20071b0
Revises: 69604d4ceebf
Create Date: 2020-08-13 11:59:59.984908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "51dfa20071b0"
down_revision = "69604d4ceebf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "auth_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "app_1_base_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("permission_group", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["permission_group"], ["auth_group.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "auth_group_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["group"], ["auth_group.id"],),
        sa.ForeignKeyConstraint(["permission"], ["auth_permission.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_group_permission")
    op.drop_table("app_1_base_user")
    op.drop_table("auth_permission")
    op.drop_table("auth_group")
    # ### end Alembic commands ###
