"""add comic model

Revision ID: b636b63c9a24
Revises: 91f4e6dd96c0
Create Date: 2020-09-11 16:02:39.224928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b636b63c9a24"
down_revision = "91f4e6dd96c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_1_comics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book", sa.Integer(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book"],
            ["app_1_book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_1_comics")
    # ### end Alembic commands ###
