"""rename permission_role to role

Revision ID: 1b8195582cdd
Revises: b636b63c9a24
Create Date: 2020-09-11 23:22:58.470374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b8195582cdd"
down_revision = "b636b63c9a24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_1_base_user", sa.Column("role", sa.Integer(), nullable=True))
    op.drop_constraint(
        "app_1_base_user_permission_role_fkey", "app_1_base_user", type_="foreignkey"
    )
    op.create_foreign_key(None, "app_1_base_user", "auth_role", ["role"], ["id"])
    op.drop_column("app_1_base_user", "permission_role")
    op.add_column("app_1_custom_user", sa.Column("role", sa.Integer(), nullable=True))
    op.drop_constraint(
        "app_1_custom_user_permission_role_fkey",
        "app_1_custom_user",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "app_1_custom_user", "auth_role", ["role"], ["id"])
    op.drop_column("app_1_custom_user", "permission_role")
    op.add_column("app_2_base_user", sa.Column("role", sa.Integer(), nullable=True))
    op.drop_constraint(
        "app_2_base_user_permission_role_fkey", "app_2_base_user", type_="foreignkey"
    )
    op.create_foreign_key(None, "app_2_base_user", "auth_role", ["role"], ["id"])
    op.drop_column("app_2_base_user", "permission_role")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_2_base_user",
        sa.Column("permission_role", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "app_2_base_user", type_="foreignkey")
    op.create_foreign_key(
        "app_2_base_user_permission_role_fkey",
        "app_2_base_user",
        "auth_role",
        ["permission_role"],
        ["id"],
    )
    op.drop_column("app_2_base_user", "role")
    op.add_column(
        "app_1_custom_user",
        sa.Column("permission_role", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "app_1_custom_user", type_="foreignkey")
    op.create_foreign_key(
        "app_1_custom_user_permission_role_fkey",
        "app_1_custom_user",
        "auth_role",
        ["permission_role"],
        ["id"],
    )
    op.drop_column("app_1_custom_user", "role")
    op.add_column(
        "app_1_base_user",
        sa.Column("permission_role", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "app_1_base_user", type_="foreignkey")
    op.create_foreign_key(
        "app_1_base_user_permission_role_fkey",
        "app_1_base_user",
        "auth_role",
        ["permission_role"],
        ["id"],
    )
    op.drop_column("app_1_base_user", "role")
    # ### end Alembic commands ###
