"""add nb borrowings

Revision ID: 4b6d0492a060
Revises: e28d40a3770c
Create Date: 2020-09-19 22:14:48.073990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b6d0492a060"
down_revision = "e28d40a3770c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_1_book", sa.Column("borrowings", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_1_book", "borrowings")
    # ### end Alembic commands ###
