"""add price_bought

Revision ID: 61a5112a9f2a
Revises: 4b6d0492a060
Create Date: 2020-09-20 11:05:13.044470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61a5112a9f2a"
down_revision = "4b6d0492a060"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_1_book", sa.Column("price_bought", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_1_book", "price_bought")
    # ### end Alembic commands ###
