"""initial revision

Revision ID: e28d40a3770c
Revises: 69604d4ceebf
Create Date: 2020-09-15 11:18:51.141736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e28d40a3770c"
down_revision = "69604d4ceebf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_1_base_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "app_1_book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("publication_date", sa.DateTime(), nullable=False),
        sa.Column(
            "book_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "app_1_custom_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "app_2_base_user",
        sa.Column("sex", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "auth_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "auth_role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "app_1_comics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("book", sa.Integer(), nullable=False),
        sa.Column("artist", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book"],
            ["app_1_book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "auth_role_permission",
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("permission", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission"], ["auth_permission.id"], name="permission_fk"
        ),
        sa.ForeignKeyConstraint(["role"], ["auth_role.id"], name="role_fk"),
        sa.PrimaryKeyConstraint("role", "permission"),
    )
    op.create_table(
        "auth_user_role",
        sa.Column("user", sa.Integer(), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role"],
            ["auth_role.id"],
        ),
        sa.ForeignKeyConstraint(["role"], ["auth_role.id"], name="role_fk"),
        sa.ForeignKeyConstraint(
            ["user"],
            ["app_1_base_user.id"],
        ),
        sa.ForeignKeyConstraint(["user"], ["app_1_base_user.id"], name="user_fk"),
        sa.PrimaryKeyConstraint("user", "role"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_user_role")
    op.drop_table("auth_role_permission")
    op.drop_table("app_1_comics")
    op.drop_table("auth_role")
    op.drop_table("auth_permission")
    op.drop_table("app_2_base_user")
    op.drop_table("app_1_custom_user")
    op.drop_table("app_1_book")
    op.drop_table("app_1_base_user")
    # ### end Alembic commands ###
