from datetime import timedelta


SETTINGS_RULES = {
    "REQUIRED_SETTINGS": [
        "SECRET_KEY",
        "AUTH_USER_MODEL"
    ]
}

JWT_ALGORITHM = "HS256"
JWT_EXPIRE_MINUTES = 15
JWT_VERIFY_EXPIRATION = True
JWT_VERIFY = True
JWT_PREFIX = "JWT"
JWT_EXPIRATION_DELTA = timedelta(seconds=60 * 5)
JWT_REFRESH_EXPIRATION_DELTA = timedelta(days=7)
JWT_REFRESH_ENABLED = True
JWT_AUDIENCE = None
JWT_ISSUER = None
JWT_LEEWAY = 0
JWT_BLACKLIST_ENABLED = False
JWT_BLACKLIST_TOKEN_CHECKS = ["access", "refresh"]

# JWT_ACCESS_LOCATION = "headers"
# JWT_REFRESH_LOCATION = "headers"
# JWT_ACCESS_COOKIE_NAME = "access_token"
# JWT_REFRESH_COOKIE_NAME = "refresh_token"

HASH_ALGORITHM = "bcrypt"
