# A separated coverage workflow avoid using `pull_request_target` event when running tests

name: Coverage
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Artifact coverage
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: test.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: coverage

      - name: Upload coverage
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: coverage.xml
